name: Docs Lint

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'README.md'
      - 'ROCKETSHIP_PROJECT_BRIEF.md'
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'README.md'
      - 'ROCKETSHIP_PROJECT_BRIEF.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Lint Markdown files
        run: |
          markdownlint-cli2 'docs/**/*.md' 'README.md' 'ROCKETSHIP_PROJECT_BRIEF.md'