name: 'Generate Schema Mocks'
on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
jobs:
  gen-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm --filter @rocketship/core run ts-node packages/core/scripts/gen-mocks.ts
      - run: git diff --exit-code  # Fail if mocks change unexpectedly